FROM quay.io/heidecke/python:latest

MAINTAINER Luke Heidecke <lh@linux.com>

#https://hub.docker.com/r/chriswayg/toolbox/~/dockerfile/

#net-tools inetutils-ping bash-completion tmux openssh-client

#python
#docker

#zsh
#bash

#ansible
#terraform

#vim

#htop
#psmisc
#strace
#dstat
#tcpdump


#bind-utils
#ldns-utils
#net-tools

#dig
#nslookup

#nc6
#openssh-clients
#findutils
#jq

#stress

#httpie
#wget
#curl

#gcloud
#azure-cli
#awscli

#etcdctl
#calicoctl
#kubectl

CMD 
